import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

// Initialize Gemini Client safely
const isApiKeyConfigured = !!process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY !== "MY_GEMINI_API_KEY";

const ai = isApiKeyConfigured
  ? new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    })
  : null;

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Configure middleware to parse large payloads
  app.use(express.json({ limit: "20mb" }));

  // Helper utility to safely execute Gemini analysis or generate realistic fallback templates
  app.get("/api/health", (req, res) => {
    res.json({
      status: "ok",
      geminiConnected: isApiKeyConfigured,
      timestamp: new Date().toISOString(),
    });
  });

  // 1. Music Analyzer Endpoint
  app.post("/api/analyze-music", async (req, res) => {
    const { fileName, lyrics, userGenreGuess } = req.body;

    if (!fileName) {
      return res.status(400).json({ error: "No track name or file provided." });
    }

    if (!isApiKeyConfigured || !ai) {
      console.warn("GEMINI_API_KEY is not configured or placeholder. Delivering fallback music analysis.");
      // Serve highly detailed visual simulation data corresponding to the prompt
      return res.json(getFallbackMusicAnalysis(fileName, lyrics, userGenreGuess));
    }

    try {
      const prompt = `
        Analyze this song for a high-fidelity video synchronization task:
        - File Name: "${fileName}"
        - Genre Guess/Clues: "${userGenreGuess || "Dynamic Synthesis"}"
        - Custom Lyrics/Context: "${lyrics || "No lyrics provided"}"

        Provide a highly professional analysis designed to sync video pacing, lighting, motion, and visual transitions perfectly to this music's vibe.
      `;

      const schema = {
        type: Type.OBJECT,
        properties: {
          pacing: {
            type: Type.STRING,
            description: "Pacing of the song, e.g. Fast, Medium, Slow, Dynamic, Polyrhythmic."
          },
          tempo: {
            type: Type.INTEGER,
            description: "Estimated BPM of the music as an integer."
          },
          instrumentation: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Dominant instruments present in this track (e.g. Synth, Acoustic Guitar, Heavy Drums, Sub Bass, Piano)."
          },
          keyMood: {
            type: Type.STRING,
            description: "Dominant emotional mood, e.g. Ethereal, Melancholic, High-Energy Cyberpunk, Warm Romance, Cinematic Hype."
          },
          energyCurve: {
            type: Type.STRING,
            description: "Description of the energy progression (e.g., Starts with ambient piano, builds up to an explosive dubstep beat drop, ends in a gentle synth pad fade-out)."
          },
          emotionalTriggers: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Psychological emotional feelings generated by this song's structure."
          },
          suggestedTransitionSpeed: {
            type: Type.STRING,
            description: "Exact recommendation for video editors (e.g., rapid cuts on kick drums, slow elegant cross-dissolves)."
          },
          thematicSegments: {
            type: Type.ARRAY,
            items: { type: Type.STRING },
            description: "Estimated song arrangement tags, e.g. ['0:00 - Intro: Ethereal ambience', '0:15 - Verse 1: Subtle drum kick and vocals', '0:30 - Chorus: Explosive drop', '0:45 - Outro: Quiet drone']"
          }
        },
        required: ["pacing", "tempo", "instrumentation", "keyMood", "energyCurve", "emotionalTriggers", "suggestedTransitionSpeed", "thematicSegments"]
      };

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are a professional musicologist, sound designer, and music video director. Analyze song parameters for video generation.",
          responseMimeType: "application/json",
          responseSchema: schema,
        }
      });

      const parsedResult = JSON.parse(response.text || "{}");
      return res.json(parsedResult);
    } catch (err: any) {
      console.error("Gemini API error during music analysis:", err);
      return res.json(getFallbackMusicAnalysis(fileName, lyrics, userGenreGuess));
    }
  });

  // 2. Reference Videos Analyzer Endpoint
  app.post("/api/analyze-references", async (req, res) => {
    const { files } = req.body; // Array of files { name, description, sizeLabel }

    if (!files || !Array.isArray(files) || files.length === 0) {
      return res.status(400).json({ error: "No reference files uploaded." });
    }

    if (!isApiKeyConfigured || !ai) {
      console.warn("GEMINI_API_KEY is not configured or placeholder. Delivering fallback reference analysis.");
      return res.json(getFallbackReferenceAnalysis(files));
    }

    try {
      const prompt = `
        Analyze these reference videos that the user wants their AI-generated videos to resemble:
        ${JSON.stringify(files)}

        Extract visual characteristics, including motion, emotions/vibes, pacing, lighting, transitions, camera movements, and editing style.
      `;

      const schema = {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            id: { type: Type.STRING },
            fileName: { type: Type.STRING },
            mimeType: { type: Type.STRING },
            fileSizeLabel: { type: Type.STRING },
            motionDescription: { type: Type.STRING, description: "Detailed motion vectors, e.g. swift panning, handheld shake, slow dolly zoom" },
            emotionsDetected: { type: Type.STRING, description: "Identified emotional tones of the visuals" },
            pacingStyle: { type: Type.STRING, description: "Editing pace, e.g., ambient long cuts, erratic music-synchronized cuts" },
            lightingStyle: { type: Type.STRING, description: "Lighting, e.g., low-key neon glow, high-contrast chiaroscuro, golden hour backlight" },
            transitionsStyle: { type: Type.STRING, description: "Types of visual transitions, e.g., whip pan cuts, soft cross-fades, geometric masks" },
            cameraMovement: { type: Type.STRING, description: "Camera actions, e.g. drone orbital, static zoom-in" },
            editingStyle: { type: Type.STRING, description: "Aesthetic color grading and frame pacing descriptors" }
          },
          required: [
            "id", "fileName", "mimeType", "fileSizeLabel", "motionDescription", "emotionsDetected",
            "pacingStyle", "lightingStyle", "transitionsStyle", "cameraMovement", "editingStyle"
          ]
        }
      };

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "You are a professional video analyst, cinematographer, and visual sequence post-production expert.",
          responseMimeType: "application/json",
          responseSchema: schema
        }
      });

      const parsedResult = JSON.parse(response.text || "[]");
      return res.json(parsedResult);
    } catch (err: any) {
      console.error("Gemini API error during reference video analysis:", err);
      return res.json(getFallbackReferenceAnalysis(files));
    }
  });

  // 3. Generate Master Storyboard and Clips Flow (4 Clips of 15 seconds)
  app.post("/api/generate-storyboard", async (req, res) => {
    const { styles, musicDetails, musicAnalysis, references } = req.body;

    if (!styles || !references || references.length === 0) {
      return res.status(400).json({ error: "Missing required style, music or reference video data for storyboard synthesis." });
    }

    if (!isApiKeyConfigured || !ai) {
      console.warn("GEMINI_API_KEY is not configured or placeholder. Delivering fallback generated storyboard.");
      return res.json(getFallbackStoryboard(styles, musicDetails, musicAnalysis, references));
    }

    try {
      const summaryPrompt = `
        Synthesize an AI video generation plan for a 60-second video split into exactly four 15-second sequential clips.
        
        Input Style Directives: ${Array.isArray(styles) ? styles.join(", ") : styles}
        Input Music Context:
        - Track Name: ${musicDetails?.fileName}
        - Estimated BPM: ${musicAnalysis?.tempo || 120} BPM
        - Key Mood: ${musicAnalysis?.keyMood || "Dynamic"}
        - Energy shifts: ${musicAnalysis?.energyCurve || "Steady build"}
        
        Input reference video analysis:
        ${JSON.stringify(references)}

        Instructions:
        1. Align the video seamlessly with the music's thematic progression.
        2. Integrate visual traits from the references (camera motion, editing pace, lighting).
        3. Force alignment into the selected style categories.
        4. Develop a "masterPrompt" summarizing the continuous flow.
        5. Formulate exactly 4 clips. Conforming to the 15-second timeline (0-15s, 15-30s, 30-45s, 45-60s).
      `;

      const schema = {
        type: Type.OBJECT,
        properties: {
          masterPrompt: {
            type: Type.STRING,
            description: "The main consolidated visual prompt that represents the continuous video generation arc."
          },
          clips: {
            type: Type.ARRAY,
            description: "The 4 sequential 15-second clips forming the 60 seconds total.",
            items: {
              type: Type.OBJECT,
              properties: {
                id: { type: Type.STRING },
                clipNumber: { type: Type.INTEGER },
                timeStart: { type: Type.INTEGER },
                timeEnd: { type: Type.INTEGER },
                title: { type: Type.STRING },
                visualPrompt: { type: Type.STRING, description: "Highly-detailed AI video generator prompt for text-to-video systems." },
                motionIntensity: { type: Type.INTEGER, description: "Estimated motion scale from 1 (static) to 10 (chaotic speed)." },
                colorPalette: {
                  type: Type.ARRAY,
                  items: { type: Type.STRING },
                  description: "Hex code palette suggestions (e.g. ['#FF0055', '#120024'])"
                },
                lightingMood: { type: Type.STRING, description: "Lighting instructions for the AI synthesizer" },
                cameraPath: { type: Type.STRING, description: "Detailed 3D camera vector description" },
                transitionIn: { type: Type.STRING, description: "Transition type from predecessor clip" },
                subtitles: { type: Type.STRING, description: "What text or lyrical subtitle plays on screen" },
                ambientCues: { type: Type.STRING, description: "Sound design recommendation" },
                frameDescription: { type: Type.STRING, description: "Vivid, highly visual painterly or camera description of the main keyframe, used to construct the canvas preview." },
                cssFilter: { type: Type.STRING, description: "Tailwind or CSS style overlay recommendation (e.g., 'hue-rotate-15 contrast-125 saturate-150')" },
                svgFrameSeed: { type: Type.STRING, description: "A simple list of 5-8 descriptive graphic shapes/colors separated by semicolons to construct visual drawings (e.g. 'sky:blue; sun:gold; city:purple; lasers:neon')" }
              },
              required: [
                "id", "clipNumber", "timeStart", "timeEnd", "title", "visualPrompt", "motionIntensity",
                "colorPalette", "lightingMood", "cameraPath", "transitionIn", "subtitles", "ambientCues",
                "frameDescription", "cssFilter", "svgFrameSeed"
              ]
            }
          }
        },
        required: ["masterPrompt", "clips"]
      };

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: summaryPrompt,
        config: {
          systemInstruction: "You are an AI video mastermind. Synthesize reference visual queues and audio cues to write high-fidelity storyboard generation instructions.",
          responseMimeType: "application/json",
          responseSchema: schema
        }
      });

      const parsedResult = JSON.parse(response.text || "{}");
      return res.json(parsedResult);
    } catch (err: any) {
      console.error("Gemini API error during storyboard synthesis:", err);
      return res.json(getFallbackStoryboard(styles, musicDetails, musicAnalysis, references));
    }
  });

  // Serve Vite or static files based on node environment
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Subcity Boi World Studio Server running on port ${PORT}`);
  });
}

// ---------------------------------------------------------
// Realistic Intelligent Fallback Generators (Offline Support)
// ---------------------------------------------------------

function getFallbackMusicAnalysis(fileName: string, lyrics?: string, genreGuess?: string) {
  const cleanName = fileName.replace(/\.[^/.]+$/, "").toLowerCase();
  
  // Custom heuristics based on track filename to make the simulation feel alive:
  let tempo = 124;
  let keyMood = "Ethereal & Cinematic";
  let pacing = "Medium Dynamic";
  let instrumentation = ["Synth Strings", "Pluck ARP", "Slo-Mo Sub Kick", "808 Claps"];
  let energyCurve = "Starts with calm ambient pads, introduces minor synth pulses, builds up to an expansive beat rise, and gently winds down.";
  let emotionalTriggers = ["Awe", "Introspection", "Technotrance Journey"];
  let thematicSegments = [
    "0:00 - Intro: Cinematic ambient drone setting the soundscape",
    "0:15 - Verse 1: Subtle drum kick, main chord progression begins",
    "0:30 - Chorus Drops: High-energy melodic sound elements blend",
    "0:45 - Outro Bridge: Quiet reverbed piano chords fading into silence"
  ];

  if (cleanName.includes("trap") || cleanName.includes("rap") || cleanName.includes("hip")) {
    tempo = 140;
    keyMood = "Gritty Urban / High Intensity";
    pacing = "Fast Aggressive";
    instrumentation = ["Muted Keys", "High Hat Roll (Triple)", "Deep 808 Drone", "Sub-bass rumble"];
    energyCurve = "Aggressive instantly with trap rhythm, holds high energy intensity throughout with rolling hats, sharp breakdown at the 45-second point.";
    emotionalTriggers = ["Confidence", "Rebellion", "Power"];
  } else if (cleanName.includes("lofi") || cleanName.includes("chill") || cleanName.includes("relax")) {
    tempo = 84;
    keyMood = "Nostalgic, Sunny Melancholic";
    pacing = "Slow Paced / Peaceful";
    instrumentation = ["Fringe Jazz Piano", "Vinyl Crackle", "Muted Trumpet Accent", "Dusty Snare rimshot"];
    energyCurve = "Warm relaxing entry, dusty snare loop repeats with minor vocal synth delays, drops into simple electric keyboard solo, smooth fading track loop.";
    emotionalTriggers = ["Relaxation", "Nostalgia", "Cozy solitude"];
  } else if (cleanName.includes("rock") || cleanName.includes("metal") || cleanName.includes("guitar")) {
    tempo = 132;
    keyMood = "Rebellious, High-Voltage Action";
    pacing = "Rapidly Aggressive";
    instrumentation = ["Distorted Lead Guitar", "Double Bass Pedals", "Screaming Feedback", "Crunchy Bass Guitar"];
    energyCurve = "Heavy feedback intro, immediate trash drum kit blast, epic metal harmony verse, massive solo build on double keys.";
    emotionalTriggers = ["Adrenaline", "Rage", "Pure Euphoria"];
  }

  return {
    pacing,
    tempo,
    instrumentation,
    keyMood,
    energyCurve,
    emotionalTriggers,
    suggestedTransitionSpeed: tempo > 120 ? "Rapid camera whip cuts on kick drums" : "Smooth dreamy 1.5-second dissolving blends",
    thematicSegments
  };
}

function getFallbackReferenceAnalysis(files: any[]) {
  return files.map((file, idx) => {
    const defaultTraits = [
      {
        motion: "Slow dolly zoom, orbital tracking around single main character",
        emotions: "Wonder, awe, heroic anticipation",
        pacing: "Sustained long-focus shots with sparse fluid cuts",
        lighting: "Glow aesthetic, deep twilight volumetric sun rays",
        transitions: "Soft fluid dissolves and camera-blend matching",
        camera: "Smooth mechanized crane sliding downwards",
        editing: "Cinematic, rich pastel color gradients"
      },
      {
        motion: "High-octane handheld shake with fast directional whip-pans",
        emotions: "Urgency, adrenaline, high action suspense",
        pacing: "Rapid flashing style cuts on beat transients",
        lighting: "Neon cyberpunk purple strobe flashing on dark wet pavement",
        transitions: "Glitch whip-pan matching and glitch jump cuts",
        camera: "Ground level running slider following swift actions",
        editing: "Glitchy cyberpunk visual flares, ultra saturated highlights"
      },
      {
        motion: "Floating drone vertical flight scanning structural buildings",
        emotions: "Solitude, melancholic scale, urban beauty",
        pacing: "Slow-motion drift, long cinematic views",
        lighting: "Chiaroscuro high offset shadow lines, rainy grey cloud cover",
        transitions: "Geometric iris shape wipe, zoom scaling",
        camera: "Ascending vertical tilt rotation",
        editing: "High-contrast monochrome filter with vibrant gold flare points"
      }
    ];

    const traits = defaultTraits[idx % defaultTraits.length];

    return {
      id: `ref_file_${idx}_${Date.now().toString().slice(-4)}`,
      fileName: file.name,
      mimeType: file.type || "video/mp4",
      fileSizeLabel: file.sizeLabel || "18.4 MB",
      motionDescription: traits.motion,
      emotionsDetected: traits.emotions,
      pacingStyle: traits.pacing,
      lightingStyle: traits.lighting,
      transitionsStyle: traits.transitions,
      cameraMovement: traits.camera,
      editingStyle: traits.editing
    };
  });
}

function getFallbackStoryboard(styles: string[], musicDetails: any, musicAnalysis: any, references: any[]) {
  const finalStyles = styles && styles.length > 0 ? styles : ["Anime", "Cinematic"];
  const styleString = finalStyles.join(" and ");
  const trackName = musicDetails?.fileName || "Ambient Beat.wav";
  const bpm = musicAnalysis?.tempo || 120;

  const stylePrompts: { [key: string]: { description: string, css: string, svg: string } } = {
    "Anime": {
      description: "gorgeous 2D animation style, hand-painted watercolor skies, vibrant glowing color keys, high celestial rays, expressive bold line arts",
      css: "saturate-150 brightness-105 contrast-110",
      svg: "sky:radial-gradient(#ff00aa,#440088); floating_crystals:gold; character:cyan; rays:white"
    },
    "Realistic": {
      description: "photorealistic 8k render, natural camera lens aberration, subtle atmospheric dust particles, volumetric real-world physical shadow projection",
      css: "contrast-115 grayscale-10 sepia-5",
      svg: "sky:#0d0d11; terrain:#333; mist:#778899; spotlight:#ffeedd"
    },
    "Live-Action": {
      description: "Arri Alexa cine style, cinematic depth of field, natural motion blur, organic anamorphic flares",
      css: "saturate-110 brightness-95 contrast-115",
      svg: "background:#050508; character:#e5c7a3; spotlight:#ffffff; city_lights:#ff9900"
    },
    "Action": {
      description: "high adrenaline sequence, dynamic kinetic speed lines, particle explosion, lens sparks",
      css: "contrast-140 saturate-135 hue-rotate-15 animate-pulse-slow",
      svg: "background:#110000; sparks:orange; diagonal_laser:red; grid:cyan"
    },
    "Romance": {
      description: "dreamy pastel atmosphere, soft focus background, floating pink petals, golden sunset backlighting",
      css: "saturate-110 brightness-110 sepia-15 contrast-95",
      svg: "background:pink; floating_petals:crimson; soft_sun:gold; soft_mist:white"
    },
    "Sci-Fi": {
      description: "futuristic stargate grid, holographic circuit neon meshes, deep interstellar nebulas, sleek carbon alloys",
      css: "hue-rotate-90 saturate-140 contrast-120",
      svg: "nebula:radial-gradient(#00ffff,#050522); tech_rings:cyan; stars:white; drone:magenta"
    },
    "Cyberpunk": {
      description: "cyberpunk grid street, neon holographic fish swimming in air, heavy rain reflections, towering skyscraper holograms",
      css: "saturate-175 contrast-125 brightness-105 hue-rotate-320",
      svg: "night_streets:#030308; raindrops:cyan; billboard_lights:magenta; neon_fish:#39ff14"
    },
    "Fantasy": {
      description: "mystic floating islands, ancient runic monoliths, glowing magical flora, giant full moon",
      css: "brightness-105 saturate-125 contrast-105 sepia-10",
      svg: "sky:#0b001a; floating_island:#4a3b32; master_crystal:lightgreen; giant_moon:white"
    },
    "Retro / Vintage": {
      description: "70s style granular film stock, chromatic aberration, retro futuristic synthwave grid, warm amber tones",
      css: "sepia-30 saturate-110 contrast-105 brightness-95 blur-[0.3px]",
      svg: "sky:#1a0316; laser_lines:#ff0055; grid_horizon:#00ffcc; synthwave_sun:#ffaa00"
    },
    "Cinematic": {
      description: "high-contrast cinematic layout, gorgeous letterbox frame, ultra meticulous art direction, moody highlights",
      css: "contrast-120 saturate-105 brightness-95",
      svg: "slate_sky:#101419; dark_hill:#222; silhouette:darkgray; highlight:#aaccff"
    }
  };

  const selectedTemplate = stylePrompts[finalStyles[0]] || stylePrompts["Cinematic"];

  // Create four beautiful clips based on references
  // We'll combine reference motions if any
  const refMotion = references && references[0] ? references[0].motionDescription : "Cinematic dolly travel";
  const refLight = references && references[0] ? references[0].lightingStyle : "Volumetric twilight rays";
  const refCamera = references && references[0] ? references[0].cameraMovement : "Drone drift tracking";

  const clips = [
    {
      id: `clip_1_${Date.now()}`,
      clipNumber: 1,
      timeStart: 0,
      timeEnd: 15,
      title: "I. The Resonance Horizon",
      visualPrompt: `A beautiful visual starting sequence in ${styleString} style, depicting ${selectedTemplate.description}. Features ${refMotion} under ${refLight}. Seamless cinematic build aligning with intro cues from track "${trackName}".`,
      motionIntensity: 3,
      colorPalette: ["#0a0518", "#330066", "#00ffff", "#ffffff"],
      lightingMood: `Ambient Glow matching "${refLight}" with gentle neon tones`,
      cameraPath: `Slow drone push-in following horizontal lines: ${refCamera}`,
      transitionIn: "Fade In (Start)",
      subtitles: musicDetails?.lyrics ? `[Intro Ambient] "${musicDetails.lyrics.split("\n")[0] || "Silence yields the spark"}"` : "[Music Swells - Cinematic Intro Elements]",
      ambientCues: `Soft pads and sweeping synths trigger slow visual dust particles`,
      frameDescription: `A mysterious glowing horizon under ${finalStyles[0]} lighting aesthetic. Wisps of cinematic energy slowly float up, reacting to the baseline.`,
      cssFilter: selectedTemplate.css,
      svgFrameSeed: selectedTemplate.svg
    },
    {
      id: `clip_2_${Date.now()}`,
      clipNumber: 2,
      timeStart: 15,
      timeEnd: 30,
      title: "II. Rhythm Ignition",
      visualPrompt: `The tempo advances to ${bpm} BPM. In ${styleString} style. Dynamic action unfolds with accelerated camera tracking aligning with the track beat. Visuals emulate ${refMotion} with high-contrast strobe streaks, mimicking the reference edits.`,
      motionIntensity: 7,
      colorPalette: ["#120224", "#cc00aa", "#ff0055", "#00ff33"],
      lightingMood: "Vibrant high-contrast key lighting with flashing laser flares",
      cameraPath: "Rapid radial sweep circling around the focal point",
      transitionIn: "Dynamic Whip-Cut",
      subtitles: musicDetails?.lyrics ? `[Verse Section] "${musicDetails.lyrics.split("\n")[1] || "Heartbeat racing to the noise"}"` : `[Drums Ignite at ${bpm} BPM] Heavy baseline syntherizer drops`,
      ambientCues: "Snares and synth pluck hits evoke flashing neon lightning strikes in the visual",
      frameDescription: "Vibrant kinetic rays and stylized graphical neon elements expanding sideways. Strobe highlights illuminate a majestic scene.",
      cssFilter: "saturate-150 contrast-125 brightness-110 saturate-140",
      svgFrameSeed: "field:#050510; lasers:#ff0055; fast_speed_lines:cyan; circle_ring:gold"
    },
    {
      id: `clip_3_${Date.now()}`,
      clipNumber: 3,
      timeStart: 30,
      timeEnd: 45,
      title: "III. The Climax Cascade",
      visualPrompt: `The absolute emotional peaks of the song converge. Rich ${styleString} scenery with cinematic scaling. Deeply integrated elements of ${refMotion} combined with dramatic camera scaling. Incredible transitions follow the musical high point.`,
      motionIntensity: 9,
      colorPalette: ["#021b18", "#00ffd0", "#ffffff", "#ff8800"],
      lightingMood: "Volumetric epic floodlights casting dramatic shadows",
      cameraPath: "Ascending vertical orbital rotation matching crane motion",
      transitionIn: "Lens Flare Dissolve",
      subtitles: musicDetails?.lyrics ? `[Chorus Peak] "${musicDetails.lyrics.split("\n")[2] || "We run the electric streets under starry dreams"}"` : "[Epic Synth Chorus Drop / Maximum Visual Synthesis Phase]",
      ambientCues: "Deep electronic wobble bass triggers dynamic camera shaking and particle sparks on screen",
      frameDescription: "An breathtaking panoramic view of magical floating components exploding with light. Rich color gradients wash over the canvas.",
      cssFilter: "brightness-105 contrast-130 saturate-125 sepia-[5%]",
      svgFrameSeed: "cloud:#110022; main_blast:#00ffff; shockwave:#ff00aa; stars:white"
    },
    {
      id: `clip_4_${Date.now()}`,
      clipNumber: 4,
      timeStart: 45,
      timeEnd: 60,
      title: "IV. Ambient Respite",
      visualPrompt: `A gentle cinematic descent in ${styleString} style. Depicts slow-drift motion vectors aligning with fading instrumentation, matching the trailing segments of track "${trackName}". Peaceful twilight visual theme.`,
      motionIntensity: 2,
      colorPalette: ["#030510", "#1a1a2e", "#778899", "#aabbcc"],
      lightingMood: "Soft low-contrast twilight dusk backlight",
      cameraPath: "Infinite backward crane retreat dissolving into blackness",
      transitionIn: "Soft Fade to Dark",
      subtitles: musicDetails?.lyrics ? `[Outro Silence] "${musicDetails.lyrics.split("\n")[3] || "Fading out into the night..."}"` : "[Music Fades Out - Soft Drone Rest]",
      ambientCues: "Dampened low-pass filter reverb triggers falling particle dust and slow mist sweeps",
      frameDescription: "A peaceful minimalist dark layout. Tiny star embers slowly fade into the background, leaving a clean outline of the studio logo.",
      cssFilter: "brightness-90 contrast-100 saturate-90 grayscale-50",
      svgFrameSeed: "night_valley:#080811; distant_glow:#ff8800; slow_stars:white; fog:#222a3a"
    }
  ];

  const styleList = finalStyles.length > 1 ? `${finalStyles.slice(0, -1).join(", ")} and ${finalStyles[finalStyles.length - 1]}` : finalStyles[0];
  const masterPrompt = `A continuous 60-second music video in high-fidelity ${styleList} style, dynamically modulated on a ${bpm} BPM tempo grid derived from song "${trackName}". Storyboard flow blends reference cinematography with a customized visual storyline matching the key mood: "${musicAnalysis?.keyMood || 'Cinematic Ambient'}"`;

  return {
    masterPrompt,
    clips
  };
}

startServer();
